### ISSUE TITLE
[IMPROVE] Missing API Keys is not always clear

### ISSUE THREAD

**Issue by JerBouma** [GamestonkTerminal/GamestonkTerminal#1307]
**What's the feature that should be improved?**
Within Stocks --> Behavioural Analysis the function 'stats' return 'No sentiment stats found.' both when there is no data and when you entered an invalid API key. Same goes for the Reddit and SentimentInvestor functionalities.

**Describe how you would like the feature improved**
 When no API key is set, this should give a different message. It is unclear what is happening now.

**Possibly describe the ideal way to improve this**
If API_KEY variable has the default value, return an Error Message that API key is missing

![image](https://user-images.githubusercontent.com/46355364/152324973-3c7d3bda-cb11-41f9-8896-14a201237eb2.png)

**Comment by jmaslek** [comment]
So this is what I tried to accomplish with the `keys` command on the main menu.  

Yes we should have some better handling, but what if you accidentally copy a 0 instead of a O?  You will likely receive the same empty data, but we would not know if it is because a bad request or because the API key (which we can really just check that it is not "REPLACE_ME".

**Comment by DidierRLopes** [comment]
@colin99d is this fixed?

**Comment by colin99d** [comment]
For everything but the stocks menu. Once we get the terminal.py PR merged I will start working on the rest of the bugs.

**Comment by colin99d** [comment]
Now that I am ready this all the way my bug fixes will not fix this. We should probably discuss a system where every time we try to grab an API key it checks if it exists and then displays warnings accordingly.
