### ISSUE TITLE
[Bug] Portfolio/Efficient Frontier - victim of global style changes. No labels, no title, no efficient frontier line

### ISSUE THREAD

**Issue by deeleeramone** [GamestonkTerminal/GamestonkTerminal#1385]
All labels have been removed, no title. 

![Screen Shot 2022-02-16 at 11 46 22 AM](https://user-images.githubusercontent.com/85772166/154344199-36bc154c-b684-4d16-929f-e9e526ccb767.png)

Old image, and since then each large dots (assets) were given individual names as equity symbol. 

![](https://user-images.githubusercontent.com/85772166/147480056-27682fb8-4087-44ff-acdc-4dcb931ea674.png)

**Comment by deeleeramone** [comment]
an update to this: restarted and the missing things show up. Good news! On that note, the legend is in an unfortunate position, the legend label for "assets" didn't change from Black to White.

**Comment by jmaslek** [comment]
So I removed the assets since they are individually labeled.  To keep with convention I changed the legend to be loc="best" and make sure it was defined after everything was drawn (initially it was drawn just after the Ef yellow curve).  Putting the legend outside the axis made It look like an additional title.

![EF1](https://user-images.githubusercontent.com/18151143/154554375-89b5c52f-47d9-4359-b44c-90c1d55a4d53.png)
