### ISSUE TITLE
[IMPROVE] Release History

### ISSUE THREAD

**Issue by nickatnight** [GamestonkTerminal/GamestonkTerminal#215]
**What's the feature that should be improved?**
It doesn't seem there is any release history. How are changes, fixes, etc being tracked?

**Describe how you would like the feature improved**
Leverage"Releases" feature that comes standard with all GitHub repos

**Possibly describe the ideal way to improve this**
There are a few options. Can add release step in GitHub actions, or manually release using any [modern](https://github.com/release-it/release-it) package

**Comment by DidierRLopes** [comment]
So far we have been disclosing this on our twitter https://twitter.com/gamestonkt or on our #new-features channel in discord (https://discord.gg/56B7KEUyZY).

We will gh actions for this once we have a `GST 1.0`. Currently we are developing at a very fast pace, and changelogs would be very big with lots of new features.

Closing this because this is in our roadmap, and we haven't had any "official release" yet.
