### ISSUE TITLE
[IMPROVE] Eliminate the need to load a ticker to access reddit behavioral analysis 

### ISSUE THREAD

**Issue by sug4ndh** [GamestonkTerminal/GamestonkTerminal#747]
**What's the feature that should be improved?**
The BA menu does not get activated until a ticker is loaded. However, the results from reddit inside the ba menu seem unrelated to the ticker viz. 
   wsb           show what WSB gang is up to in subreddit wallstreetbets
   watchlist     show other users watchlist
   popular       show popular tickers
   spac_c        show other users spacs announcements from subreddit SPACs community
   spac          show other users spacs announcements from other subs

**Describe how you would like the feature improved**
I don't think there is any need to load a ticker to access the behavioral analysis from reddit as they seem completely unrelated to the loaded ticker.

**Possibly describe the ideal way to improve this**
Create a separate menu for reddit in the stocks menu.

**Comment by DidierRLopes** [comment]
Hey @sug4ndh,

We are going individually through each of the menus and refactor the code substantially. The behavioural analysis is one of the few that we have to refactor, and what you said is definitely part of the refactoring :)

We'll keep the commands all in the same menu, with the difference of having some "greyed out" and others not based on ticker loaded. Also, we'll allow the user to load a ticker inside the terminal so that you don't need to leave that menu to load a different ticker and go back in

**Comment by sug4ndh** [comment]
Okay, thanks! :)
